# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.node_api import NodeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNodeApi(unittest.TestCase):
    """NodeApi unit test stubs"""

    def setUp(self):
        self.api = NodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_get(self):
        """Test case for info_get

        """
        pass

    def test_links_get(self):
        """Test case for links_get

        """
        pass

    def test_mheard_port_get(self):
        """Test case for mheard_port_get

        """
        pass

    def test_nodes_get(self):
        """Test case for nodes_get

        """
        pass

    def test_ports_get(self):
        """Test case for ports_get

        """
        pass

    def test_users_get(self):
        """Test case for users_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
