# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_info_response import GetInfoResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetInfoResponse(unittest.TestCase):
    """GetInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInfoResponse(self):
        """Test GetInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_info_response.GetInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
