# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_management_api import MailManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailManagementApi(unittest.TestCase):
    """MailManagementApi unit test stubs"""

    def setUp(self):
        self.api = MailManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mail_management_options_get(self):
        """Test case for mail_management_options_get

        """
        pass

    def test_mail_management_partners_get(self):
        """Test case for mail_management_partners_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
