# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_links_response import GetLinksResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetLinksResponse(unittest.TestCase):
    """GetLinksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetLinksResponse(self):
        """Test GetLinksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_links_response.GetLinksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
