# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_users_response import GetUsersResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetUsersResponse(unittest.TestCase):
    """GetUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUsersResponse(self):
        """Test GetUsersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_users_response.GetUsersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
