# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ForwardingStation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'queue_length': 'int',
        'forwarding_config': 'ForwardingConfig'
    }

    attribute_map = {
        'queue_length': 'queueLength',
        'forwarding_config': 'forwardingConfig'
    }

    def __init__(self, queue_length=None, forwarding_config=None):  # noqa: E501
        """ForwardingStation - a model defined in Swagger"""  # noqa: E501
        self._queue_length = None
        self._forwarding_config = None
        self.discriminator = None
        if queue_length is not None:
            self.queue_length = queue_length
        if forwarding_config is not None:
            self.forwarding_config = forwarding_config

    @property
    def queue_length(self):
        """Gets the queue_length of this ForwardingStation.  # noqa: E501


        :return: The queue_length of this ForwardingStation.  # noqa: E501
        :rtype: int
        """
        return self._queue_length

    @queue_length.setter
    def queue_length(self, queue_length):
        """Sets the queue_length of this ForwardingStation.


        :param queue_length: The queue_length of this ForwardingStation.  # noqa: E501
        :type: int
        """

        self._queue_length = queue_length

    @property
    def forwarding_config(self):
        """Gets the forwarding_config of this ForwardingStation.  # noqa: E501


        :return: The forwarding_config of this ForwardingStation.  # noqa: E501
        :rtype: ForwardingConfig
        """
        return self._forwarding_config

    @forwarding_config.setter
    def forwarding_config(self, forwarding_config):
        """Sets the forwarding_config of this ForwardingStation.


        :param forwarding_config: The forwarding_config of this ForwardingStation.  # noqa: E501
        :type: ForwardingConfig
        """

        self._forwarding_config = forwarding_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForwardingStation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForwardingStation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
