# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'mid': 'str',
        'rcvd': 'int',
        'type': 'str',
        'status': 'str',
        'to': 'str',
        '_from': 'str',
        'size': 'int',
        'subject': 'str'
    }

    attribute_map = {
        'id': 'id',
        'mid': 'mid',
        'rcvd': 'rcvd',
        'type': 'type',
        'status': 'status',
        'to': 'to',
        '_from': 'from',
        'size': 'size',
        'subject': 'subject'
    }

    def __init__(self, id=None, mid=None, rcvd=None, type=None, status=None, to=None, _from=None, size=None, subject=None):  # noqa: E501
        """Message - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._mid = None
        self._rcvd = None
        self._type = None
        self._status = None
        self._to = None
        self.__from = None
        self._size = None
        self._subject = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if mid is not None:
            self.mid = mid
        if rcvd is not None:
            self.rcvd = rcvd
        if type is not None:
            self.type = type
        if status is not None:
            self.status = status
        if to is not None:
            self.to = to
        if _from is not None:
            self._from = _from
        if size is not None:
            self.size = size
        if subject is not None:
            self.subject = subject

    @property
    def id(self):
        """Gets the id of this Message.  # noqa: E501


        :return: The id of this Message.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Message.


        :param id: The id of this Message.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def mid(self):
        """Gets the mid of this Message.  # noqa: E501


        :return: The mid of this Message.  # noqa: E501
        :rtype: str
        """
        return self._mid

    @mid.setter
    def mid(self, mid):
        """Sets the mid of this Message.


        :param mid: The mid of this Message.  # noqa: E501
        :type: str
        """

        self._mid = mid

    @property
    def rcvd(self):
        """Gets the rcvd of this Message.  # noqa: E501


        :return: The rcvd of this Message.  # noqa: E501
        :rtype: int
        """
        return self._rcvd

    @rcvd.setter
    def rcvd(self, rcvd):
        """Sets the rcvd of this Message.


        :param rcvd: The rcvd of this Message.  # noqa: E501
        :type: int
        """

        self._rcvd = rcvd

    @property
    def type(self):
        """Gets the type of this Message.  # noqa: E501


        :return: The type of this Message.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Message.


        :param type: The type of this Message.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def status(self):
        """Gets the status of this Message.  # noqa: E501


        :return: The status of this Message.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Message.


        :param status: The status of this Message.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def to(self):
        """Gets the to of this Message.  # noqa: E501


        :return: The to of this Message.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this Message.


        :param to: The to of this Message.  # noqa: E501
        :type: str
        """

        self._to = to

    @property
    def _from(self):
        """Gets the _from of this Message.  # noqa: E501


        :return: The _from of this Message.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this Message.


        :param _from: The _from of this Message.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def size(self):
        """Gets the size of this Message.  # noqa: E501


        :return: The size of this Message.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this Message.


        :param size: The size of this Message.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def subject(self):
        """Gets the subject of this Message.  # noqa: E501


        :return: The subject of this Message.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this Message.


        :param subject: The subject of this Message.  # noqa: E501
        :type: str
        """

        self._subject = subject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Message, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
