# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NinoModeEnum(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GFSK9600 = "gfsk9600"
    C4FSK19200IL2PC = "c4Fsk19200Il2pc"
    GFSK9600IL2PC = "gfsk9600Il2pc"
    C4FSK9600IL2PC = "c4Fsk9600Il2pc"
    GFSK4800IL2PC = "gfsk4800Il2pc"
    QPSK3600IL2PC = "qpsk3600Il2pc"
    AFSK1200 = "afsk1200"
    AFSK1200IL2P = "afsk1200Il2p"
    BPSK300IL2PC = "bpsk300Il2pc"
    QPSK600IL2PC = "qpsk600Il2pc"
    BPSK1200IL2PC = "bpsk1200Il2pc"
    QPSK2400IL2PC = "qpsk2400Il2pc"
    AFSK300 = "afsk300"
    AFSK300IL2P = "afsk300Il2p"
    AFSK300IL2PC = "afsk300Il2pc"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """NinoModeEnum - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NinoModeEnum, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NinoModeEnum):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
