# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SendMailEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to': 'str',
        'subject': 'str',
        'type': 'str',
        'bid': 'str',
        'body': 'str'
    }

    attribute_map = {
        'to': 'to',
        'subject': 'subject',
        'type': 'type',
        'bid': 'bid',
        'body': 'body'
    }

    def __init__(self, to=None, subject=None, type=None, bid=None, body=None):  # noqa: E501
        """SendMailEntity - a model defined in Swagger"""  # noqa: E501
        self._to = None
        self._subject = None
        self._type = None
        self._bid = None
        self._body = None
        self.discriminator = None
        if to is not None:
            self.to = to
        if subject is not None:
            self.subject = subject
        if type is not None:
            self.type = type
        if bid is not None:
            self.bid = bid
        if body is not None:
            self.body = body

    @property
    def to(self):
        """Gets the to of this SendMailEntity.  # noqa: E501


        :return: The to of this SendMailEntity.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this SendMailEntity.


        :param to: The to of this SendMailEntity.  # noqa: E501
        :type: str
        """

        self._to = to

    @property
    def subject(self):
        """Gets the subject of this SendMailEntity.  # noqa: E501


        :return: The subject of this SendMailEntity.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this SendMailEntity.


        :param subject: The subject of this SendMailEntity.  # noqa: E501
        :type: str
        """

        self._subject = subject

    @property
    def type(self):
        """Gets the type of this SendMailEntity.  # noqa: E501


        :return: The type of this SendMailEntity.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SendMailEntity.


        :param type: The type of this SendMailEntity.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def bid(self):
        """Gets the bid of this SendMailEntity.  # noqa: E501


        :return: The bid of this SendMailEntity.  # noqa: E501
        :rtype: str
        """
        return self._bid

    @bid.setter
    def bid(self, bid):
        """Sets the bid of this SendMailEntity.


        :param bid: The bid of this SendMailEntity.  # noqa: E501
        :type: str
        """

        self._bid = bid

    @property
    def body(self):
        """Gets the body of this SendMailEntity.  # noqa: E501


        :return: The body of this SendMailEntity.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this SendMailEntity.


        :param body: The body of this SendMailEntity.  # noqa: E501
        :type: str
        """

        self._body = body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SendMailEntity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendMailEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
