# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimeOnly(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hour': 'int',
        'minute': 'int',
        'second': 'int',
        'millisecond': 'int',
        'microsecond': 'int',
        'nanosecond': 'int',
        'ticks': 'int'
    }

    attribute_map = {
        'hour': 'hour',
        'minute': 'minute',
        'second': 'second',
        'millisecond': 'millisecond',
        'microsecond': 'microsecond',
        'nanosecond': 'nanosecond',
        'ticks': 'ticks'
    }

    def __init__(self, hour=None, minute=None, second=None, millisecond=None, microsecond=None, nanosecond=None, ticks=None):  # noqa: E501
        """TimeOnly - a model defined in Swagger"""  # noqa: E501
        self._hour = None
        self._minute = None
        self._second = None
        self._millisecond = None
        self._microsecond = None
        self._nanosecond = None
        self._ticks = None
        self.discriminator = None
        if hour is not None:
            self.hour = hour
        if minute is not None:
            self.minute = minute
        if second is not None:
            self.second = second
        if millisecond is not None:
            self.millisecond = millisecond
        if microsecond is not None:
            self.microsecond = microsecond
        if nanosecond is not None:
            self.nanosecond = nanosecond
        if ticks is not None:
            self.ticks = ticks

    @property
    def hour(self):
        """Gets the hour of this TimeOnly.  # noqa: E501


        :return: The hour of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._hour

    @hour.setter
    def hour(self, hour):
        """Sets the hour of this TimeOnly.


        :param hour: The hour of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._hour = hour

    @property
    def minute(self):
        """Gets the minute of this TimeOnly.  # noqa: E501


        :return: The minute of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._minute

    @minute.setter
    def minute(self, minute):
        """Sets the minute of this TimeOnly.


        :param minute: The minute of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._minute = minute

    @property
    def second(self):
        """Gets the second of this TimeOnly.  # noqa: E501


        :return: The second of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._second

    @second.setter
    def second(self, second):
        """Sets the second of this TimeOnly.


        :param second: The second of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._second = second

    @property
    def millisecond(self):
        """Gets the millisecond of this TimeOnly.  # noqa: E501


        :return: The millisecond of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._millisecond

    @millisecond.setter
    def millisecond(self, millisecond):
        """Sets the millisecond of this TimeOnly.


        :param millisecond: The millisecond of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._millisecond = millisecond

    @property
    def microsecond(self):
        """Gets the microsecond of this TimeOnly.  # noqa: E501


        :return: The microsecond of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._microsecond

    @microsecond.setter
    def microsecond(self, microsecond):
        """Sets the microsecond of this TimeOnly.


        :param microsecond: The microsecond of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._microsecond = microsecond

    @property
    def nanosecond(self):
        """Gets the nanosecond of this TimeOnly.  # noqa: E501


        :return: The nanosecond of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._nanosecond

    @nanosecond.setter
    def nanosecond(self, nanosecond):
        """Sets the nanosecond of this TimeOnly.


        :param nanosecond: The nanosecond of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._nanosecond = nanosecond

    @property
    def ticks(self):
        """Gets the ticks of this TimeOnly.  # noqa: E501


        :return: The ticks of this TimeOnly.  # noqa: E501
        :rtype: int
        """
        return self._ticks

    @ticks.setter
    def ticks(self, ticks):
        """Sets the ticks of this TimeOnly.


        :param ticks: The ticks of this TimeOnly.  # noqa: E501
        :type: int
        """

        self._ticks = ticks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeOnly, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeOnly):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
