# coding: utf-8

"""
    BPQ API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class NodeApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def node_info_get(self, **kwargs):  # noqa: E501
        """node_info_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_info_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: GetInfoResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.node_info_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.node_info_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def node_info_get_with_http_info(self, **kwargs):  # noqa: E501
        """node_info_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_info_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: GetInfoResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method node_info_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/node/info', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetInfoResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def node_mheard_get(self, **kwargs):  # noqa: E501
        """node_mheard_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_mheard_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[MHeardMultiportDetails]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.node_mheard_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.node_mheard_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def node_mheard_get_with_http_info(self, **kwargs):  # noqa: E501
        """node_mheard_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_mheard_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[MHeardMultiportDetails]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method node_mheard_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/node/mheard', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[MHeardMultiportDetails]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def node_mheard_port_number_get(self, port_number, **kwargs):  # noqa: E501
        """node_mheard_port_number_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_mheard_port_number_get(port_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int port_number: (required)
        :return: dict(str, MHeardMonoportDetails)
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.node_mheard_port_number_get_with_http_info(port_number, **kwargs)  # noqa: E501
        else:
            (data) = self.node_mheard_port_number_get_with_http_info(port_number, **kwargs)  # noqa: E501
            return data

    def node_mheard_port_number_get_with_http_info(self, port_number, **kwargs):  # noqa: E501
        """node_mheard_port_number_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_mheard_port_number_get_with_http_info(port_number, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int port_number: (required)
        :return: dict(str, MHeardMonoportDetails)
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['port_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method node_mheard_port_number_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'port_number' is set
        if ('port_number' not in params or
                params['port_number'] is None):
            raise ValueError("Missing the required parameter `port_number` when calling `node_mheard_port_number_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'port_number' in params:
            path_params['portNumber'] = params['port_number']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/node/mheard/{portNumber}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='dict(str, MHeardMonoportDetails)',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def node_port_port_num_ninomode_post(self, port_num, **kwargs):  # noqa: E501
        """node_port_port_num_ninomode_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_port_port_num_ninomode_post(port_num, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int port_num: (required)
        :param int id:
        :param NinoModeEnum name:
        :param NinoModeUsage usage:
        :param bool persist:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.node_port_port_num_ninomode_post_with_http_info(port_num, **kwargs)  # noqa: E501
        else:
            (data) = self.node_port_port_num_ninomode_post_with_http_info(port_num, **kwargs)  # noqa: E501
            return data

    def node_port_port_num_ninomode_post_with_http_info(self, port_num, **kwargs):  # noqa: E501
        """node_port_port_num_ninomode_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.node_port_port_num_ninomode_post_with_http_info(port_num, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int port_num: (required)
        :param int id:
        :param NinoModeEnum name:
        :param NinoModeUsage usage:
        :param bool persist:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['port_num', 'id', 'name', 'usage', 'persist']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method node_port_port_num_ninomode_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'port_num' is set
        if ('port_num' not in params or
                params['port_num'] is None):
            raise ValueError("Missing the required parameter `port_num` when calling `node_port_port_num_ninomode_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'port_num' in params:
            path_params['portNum'] = params['port_num']  # noqa: E501

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501
        if 'usage' in params:
            query_params.append(('usage', params['usage']))  # noqa: E501
        if 'persist' in params:
            query_params.append(('persist', params['persist']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/node/port/{portNum}/ninomode', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
